import { MigrationInterface, QueryRunner } from "typeorm";

export class CourseEntity1766420510983 implements MigrationInterface {
    name = 'CourseEntity1766420510983'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."Transactions_status_enum" AS ENUM('pending', 'success', 'failure', 'abandoned')`);
        await queryRunner.query(`CREATE TYPE "public"."Transactions_paid_for_enum" AS ENUM('EVENT', 'COUNSELLING', 'COURSE', 'BOOK')`);
        await queryRunner.query(`CREATE TABLE "Transactions" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "transaction_ref" character varying, "status" "public"."Transactions_status_enum" NOT NULL DEFAULT 'pending', "comment" character varying, "email_address" character varying, "phone_number" character varying, "paid_for" "public"."Transactions_paid_for_enum" NOT NULL, "amount" numeric(10,2) DEFAULT '0', "charge" numeric(10,2) DEFAULT '0', "actualAmount" numeric(10,2) DEFAULT '0', "currency_code" character varying DEFAULT 'NGN', "hash" character varying, "paystack_ref" character varying, "userId" integer, CONSTRAINT "PK_7761bf9766670b894ff2fdb3700" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prayer_comments" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "comment" text NOT NULL, "isVisible" boolean NOT NULL DEFAULT true, "prayer_id" integer, "user_id" integer, "parent_comment_id" integer, CONSTRAINT "PK_505a94cb9763d7fd245249cc54c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prayer_comment_prayer_id" ON "prayer_comments" ("prayer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prayer_comment_user_id" ON "prayer_comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prayer_comment_parent_id" ON "prayer_comments" ("parent_comment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prayer_comment_created_at" ON "prayer_comments" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."prayer_amens_reaction_enum" AS ENUM('AMEN', 'STRONG_AMEN')`);
        await queryRunner.query(`CREATE TABLE "prayer_amens" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "reaction" "public"."prayer_amens_reaction_enum" NOT NULL DEFAULT 'AMEN', "prayer_id" integer, "user_id" integer, CONSTRAINT "uq_prayer_user" UNIQUE ("prayer_id", "user_id"), CONSTRAINT "PK_19ee26d378d211e0775fbe592a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prayer_amen_prayer_id" ON "prayer_amens" ("prayer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prayer_amen_user_id" ON "prayer_amens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "prayers" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying(160), "body" text NOT NULL, "sourceAttribution" character varying(120), "isVisible" boolean NOT NULL DEFAULT true, "isAnswered" boolean NOT NULL DEFAULT false, "answeredAt" TIMESTAMP, "isAnonymous" boolean NOT NULL DEFAULT false, "amenCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "shareCount" integer NOT NULL DEFAULT '0', "reportedCount" integer NOT NULL DEFAULT '0', "lastActivityAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_e999e971b29faf22932664580ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prayers_user_id" ON "prayers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_prayers_last_activity" ON "prayers" ("lastActivityAt") `);
        await queryRunner.query(`CREATE INDEX "idx_prayers_created_at" ON "prayers" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_prayers_is_visible" ON "prayers" ("isVisible") `);
        await queryRunner.query(`CREATE TYPE "public"."lesson_attachments_type_enum" AS ENUM('PDF', 'IMAGE', 'DOC', 'LINK', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "lesson_attachments" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "section_id" integer NOT NULL, "title" character varying NOT NULL, "type" "public"."lesson_attachments_type_enum" NOT NULL DEFAULT 'OTHER', "url" character varying NOT NULL, "publicId" character varying NOT NULL, "resourceType" character varying NOT NULL DEFAULT 'raw', "sizeBytes" integer, CONSTRAINT "PK_37484909e3479efdd8bf36c7690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_sections" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "lesson_id" integer NOT NULL, "title" character varying NOT NULL, "contentHtml" text, "youtubeUrl" character varying, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_46f8e73f0f25d4a26a2a7fd70c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3650404571311a3992c5467ae7" ON "lesson_sections" ("lesson_id", "sortOrder") `);
        await queryRunner.query(`CREATE TYPE "public"."lessons_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "course_id" integer NOT NULL, "title" character varying, "slug" character varying NOT NULL, "descriptionHtml" text, "sortOrder" integer NOT NULL DEFAULT '0', "status" "public"."lessons_status_enum" NOT NULL DEFAULT 'DRAFT', CONSTRAINT "UQ_ca2edfa23c965f9c435572a7de3" UNIQUE ("slug"), CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39a94200768edfbf102291bb34" ON "lessons" ("course_id", "sortOrder") `);
        await queryRunner.query(`CREATE TYPE "public"."courses_accesstype_enum" AS ENUM('FREE', 'PAID')`);
        await queryRunner.query(`CREATE TYPE "public"."courses_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "slug" character varying NOT NULL, "title" character varying NOT NULL, "descriptionHtml" text, "thumbnailUrl" character varying, "accessType" "public"."courses_accesstype_enum" NOT NULL DEFAULT 'FREE', "price" numeric(10,2), "currency" character varying NOT NULL DEFAULT 'NGN', "thumbnailPublicId" character varying, "thumbnailResourceType" character varying, "status" "public"."courses_status_enum" NOT NULL DEFAULT 'DRAFT', CONSTRAINT "UQ_a3bb2d01cfa0f95bc5e034e1b7a" UNIQUE ("slug"), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."UserLessonProgress_status_enum" AS ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "UserLessonProgress" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "user_id" integer NOT NULL, "course_progress_id" integer NOT NULL, "lesson_id" integer NOT NULL, "status" "public"."UserLessonProgress_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "progressPercent" double precision NOT NULL DEFAULT '0', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, CONSTRAINT "PK_9d1d2cf6b5f9acadd2b24d4a5f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3aff9a5f008a7ae618ea29f74d" ON "UserLessonProgress" ("user_id", "course_progress_id", "lesson_id") `);
        await queryRunner.query(`CREATE TYPE "public"."UserCourseProgress_status_enum" AS ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "UserCourseProgress" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "courseId" integer NOT NULL, "status" "public"."UserCourseProgress_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "progressPercent" double precision NOT NULL DEFAULT '0', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, CONSTRAINT "PK_7e8adfde3a6416e5af4eaa44d0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."course_access_kind_enum" AS ENUM('FREE', 'ONE_TIME', 'SUBSCRIPTION', 'ADMIN_GRANTED')`);
        await queryRunner.query(`CREATE TYPE "public"."course_access_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "course_access" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "courseId" integer NOT NULL, "kind" "public"."course_access_kind_enum" NOT NULL, "status" "public"."course_access_status_enum" NOT NULL DEFAULT 'ACTIVE', "startsAt" TIMESTAMP WITH TIME ZONE, "endsAt" TIMESTAMP WITH TIME ZONE, "provider" character varying, "providerRef" character varying, CONSTRAINT "PK_92d971e40ef5b4295a7f98d0c24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_02a4cae0a5ab7f68e5c63b18f5" ON "course_access" ("userId", "courseId") `);
        await queryRunner.query(`CREATE TYPE "public"."Users_auth_provider_enum" AS ENUM('local', 'google')`);
        await queryRunner.query(`CREATE TYPE "public"."Users_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."Users_marital_status_enum" AS ENUM('SINGLE', 'MARRIED')`);
        await queryRunner.query(`CREATE TABLE "Users" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "last_name" character varying NOT NULL, "auth_provider" "public"."Users_auth_provider_enum" NOT NULL DEFAULT 'local', "first_name" character varying NOT NULL, "middle_name" character varying, "gender" "public"."Users_gender_enum", "birth_date" character varying, "email_address" character varying NOT NULL, "phone_no" character varying, "password" character varying NOT NULL, "marital_status" "public"."Users_marital_status_enum", "is_parent" boolean DEFAULT false, "ResetCode" character varying, "resetTokenExpiration" TIMESTAMP, "is_email_verified" boolean NOT NULL DEFAULT false, "lastLogonDate" TIMESTAMP, "user_name" character varying, "profilePictureUrl" character varying, "profilePicturePublicId" character varying, "rejectedBy" character varying, "refresh_token" character varying, "suspensionReason" text, CONSTRAINT "UQ_83a656147925b3862df74cbbd7d" UNIQUE ("email_address"), CONSTRAINT "UQ_48e04cd7eec10c14d36cb670403" UNIQUE ("phone_no"), CONSTRAINT "UQ_325d151f1b865975f2d6e31e7f9" UNIQUE ("user_name"), CONSTRAINT "PK_16d4f7d636df336db11d87413e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ChallengeTasks_cadence_enum" AS ENUM('DAILY', 'WEEKLY')`);
        await queryRunner.query(`CREATE TABLE "ChallengeTasks" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "cadence" "public"."ChallengeTasks_cadence_enum" NOT NULL DEFAULT 'DAILY', "dayNumber" integer, "weekNumber" integer, "title" character varying NOT NULL, "instructions" text, "isMilestone" boolean NOT NULL DEFAULT false, "challengeId" integer, CONSTRAINT "PK_b9e95b2f52e8bb49a37ccb0ef3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_da6edc7fb6ce04a1591331abfb" ON "ChallengeTasks" ("challengeId") `);
        await queryRunner.query(`CREATE TYPE "public"."Challenges_community_enum" AS ENUM('SINGLE', 'MARRIED', 'PARENT')`);
        await queryRunner.query(`CREATE TYPE "public"."Challenges_frequency_enum" AS ENUM('DAILY', 'WEEKLY', 'MIXED')`);
        await queryRunner.query(`CREATE TYPE "public"."Challenges_visibility_enum" AS ENUM('PUBLIC', 'COMMUNITY_ONLY')`);
        await queryRunner.query(`CREATE TYPE "public"."Challenges_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "Challenges" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "community" "public"."Challenges_community_enum" NOT NULL, "durationDays" integer NOT NULL, "frequency" "public"."Challenges_frequency_enum" NOT NULL DEFAULT 'DAILY', "visibility" "public"."Challenges_visibility_enum" NOT NULL DEFAULT 'COMMUNITY_ONLY', "coverImageUrl" character varying, "description" text, "bookTitle" character varying, "bookAuthor" character varying, "status" "public"."Challenges_status_enum" NOT NULL DEFAULT 'DRAFT', "requireDualConfirmation" boolean NOT NULL DEFAULT false, "completionBadgeCode" character varying, CONSTRAINT "PK_849dae8b4a81ce77bd9cd89741a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b363ac79f844603c4ecfb964d9" ON "Challenges" ("title") `);
        await queryRunner.query(`CREATE TABLE "UserChallenges" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "streakCount" integer NOT NULL DEFAULT '0', "progressPercent" integer NOT NULL DEFAULT '0', "lastCheckInAt" TIMESTAMP, "isCompleted" boolean NOT NULL DEFAULT false, "isArchived" boolean NOT NULL DEFAULT false, "userId" integer, "challengeId" integer, CONSTRAINT "PK_a485894ee1209cbb67a629d70c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_51e41d4e6713142e1589f859f8" ON "UserChallenges" ("userId", "challengeId") `);
        await queryRunner.query(`CREATE TABLE "UserTaskProgress" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "completedByUser" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, "confirmedByPartner" boolean NOT NULL DEFAULT false, "partnerUserId" character varying, "confirmedAt" TIMESTAMP, "userChallengeId" integer, "taskId" integer, CONSTRAINT "PK_8df8abed0cb58ccebad303bd5b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_98b1f78ec350bd9cab8cbcfb5b" ON "UserTaskProgress" ("userChallengeId", "taskId") `);
        await queryRunner.query(`CREATE TYPE "public"."UserPurchases_itemtype_enum" AS ENUM('COURSE', 'BOOK')`);
        await queryRunner.query(`CREATE TYPE "public"."UserPurchases_status_enum" AS ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "UserPurchases" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "itemType" "public"."UserPurchases_itemtype_enum" NOT NULL, "itemId" integer NOT NULL, "status" "public"."UserPurchases_status_enum" NOT NULL DEFAULT 'PENDING', "amount" numeric(10,2) NOT NULL, "paymentRef" character varying, CONSTRAINT "PK_3880bead0f6a9478d2fd79723d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97f8e3d9c172164216e43ca238" ON "UserPurchases" ("userId", "itemType", "itemId") `);
        await queryRunner.query(`CREATE TYPE "public"."user_section_progress_status_enum" AS ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "user_section_progress" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "sectionId" integer NOT NULL, "status" "public"."user_section_progress_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "lastPositionSeconds" integer, "totalWatchedSeconds" integer, "manuallyCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_18655d4fce39a6f73a409e5bbe0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1cc397afbe76ce6dd15856e101" ON "user_section_progress" ("userId", "sectionId") `);
        await queryRunner.query(`CREATE TYPE "public"."Books_ownershiptype_enum" AS ENUM('IN_HOUSE', 'EXTERNAL')`);
        await queryRunner.query(`CREATE TYPE "public"."Books_accesstype_enum" AS ENUM('FREE', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "Books" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "slug" character varying NOT NULL, "title" character varying NOT NULL, "author" character varying, "description" text, "coverImageUrl" character varying, "coverImagePublicId" character varying, "ownershipType" "public"."Books_ownershiptype_enum" NOT NULL DEFAULT 'IN_HOUSE', "accessType" "public"."Books_accesstype_enum", "price" numeric(10,2), "currency" character varying NOT NULL DEFAULT 'NGN', "pdfUrl" text, "pdfPublicId" character varying, "externalUrl" text, "isPublished" boolean NOT NULL DEFAULT true, "publishDate" character varying, "isbn" character varying, CONSTRAINT "UQ_f3a87c78d9793df0cc6310de988" UNIQUE ("slug"), CONSTRAINT "PK_45fc00b09d337eadf83e9240157" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_book_download_ownership_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "UserBookDownloads" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "bookId" integer NOT NULL, "downloadedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "paymentRef" character varying, "status" "public"."user_book_download_ownership_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_2ac6af74046bb93cfac432cddc0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f5ec900b10e0b63ffe766311d1" ON "UserBookDownloads" ("paymentRef") WHERE "paymentRef" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_56048469fcc831362af2268273" ON "UserBookDownloads" ("userId", "bookId") `);
        await queryRunner.query(`CREATE TABLE "Badges" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "code" character varying, "name" character varying NOT NULL, "description" text, "iconUrl" character varying, CONSTRAINT "UQ_8348af2fdd47ff0fe97ab704f51" UNIQUE ("code"), CONSTRAINT "PK_1003fe1bcfbe3e128ad9daefba2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "UserBadges" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "awardedAt" TIMESTAMP, "awardedForChallengeId" character varying, "userId" integer, "badgeId" integer, CONSTRAINT "PK_9eeec7e3b1e7d79a18b97483f80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7aca27064e9a12cebda5ad8651" ON "UserBadges" ("userId", "badgeId") `);
        await queryRunner.query(`CREATE TABLE "section_attachments" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "section_id" integer NOT NULL, "name" character varying(255) NOT NULL, "url" character varying(2000) NOT NULL, "publicId" character varying(500) NOT NULL, "resourceType" character varying(50) NOT NULL, "mimeType" character varying(100), "sizeBytes" bigint, CONSTRAINT "PK_4230eb523b6676a677f3dca9f8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd9d2383c7a8cc6752a6975719" ON "section_attachments" ("section_id") `);
        await queryRunner.query(`CREATE TYPE "public"."Events_type_enum" AS ENUM('COMMUNITY', 'CONFERENCE', 'RETREAT')`);
        await queryRunner.query(`CREATE TYPE "public"."Events_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'CANCELLED', 'ENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."Events_mode_enum" AS ENUM('ONLINE', 'OFFLINE')`);
        await queryRunner.query(`CREATE TABLE "Events" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "description" text, "type" "public"."Events_type_enum" NOT NULL, "status" "public"."Events_status_enum" NOT NULL DEFAULT 'PUBLISHED', "mode" "public"."Events_mode_enum" NOT NULL, "locationText" character varying, "locationUrl" character varying, "coverImageUrl" character varying, "startsAt" TIMESTAMP NOT NULL, "endsAt" TIMESTAMP NOT NULL, "capacity" integer, "icsToken" character varying, "price" numeric, "organizerId" integer, CONSTRAINT "UQ_7220e6d399ecd253f00155a3b4d" UNIQUE ("icsToken"), CONSTRAINT "PK_efc6f7ffffa26a4d4fe5f383a0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76b3852578992c8d734d9307c6" ON "Events" ("startsAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dba9ac34c81dd23102f2e486f5" ON "Events" ("type", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."event_registration_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "EventRegistrations" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "status" "public"."event_registration_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "quantity" integer NOT NULL DEFAULT '1', "unitPrice" numeric(12,2), "paidAt" TIMESTAMP, "transaction_ref" character varying, "cancelledAt" TIMESTAMP, "userId" integer, "eventId" integer, "transactionId" integer, CONSTRAINT "PK_849eb57e54a2585e003415853a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88a8ce1237cc41db00d76b9c38" ON "EventRegistrations" ("userId", "eventId") `);
        await queryRunner.query(`CREATE TYPE "public"."Counsellings_mode_enum" AS ENUM('ONLINE', 'OFFLINE')`);
        await queryRunner.query(`CREATE TYPE "public"."Counsellings_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."Counsellings_type_enum" AS ENUM('INDIVIDUAL', 'COUPLES', 'FAMILY', 'GROUP')`);
        await queryRunner.query(`CREATE TABLE "Counsellings" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "description" text, "durationMinutes" integer NOT NULL, "mode" "public"."Counsellings_mode_enum" NOT NULL, "status" "public"."Counsellings_status_enum" NOT NULL DEFAULT 'PUBLISHED', "type" "public"."Counsellings_type_enum" NOT NULL DEFAULT 'INDIVIDUAL', "coverUrl" character varying, "price" numeric, "whatYouGet" text, "whoItsFor" text, "howItWorks" text, "counsellorNotes" text, "maxClientsPerSession" integer, "isActive" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "counsellorId" integer, CONSTRAINT "PK_08462a5793be871c74d85e13d7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9aaea653f378930280d4c4adfb" ON "Counsellings" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a84583a29ffcc0855944cada3" ON "Counsellings" ("status", "mode") `);
        await queryRunner.query(`CREATE TYPE "public"."Admins_role_enum" AS ENUM('SUPER_ADMIN', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "Admins" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email_address" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."Admins_role_enum" NOT NULL DEFAULT 'ADMIN', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, CONSTRAINT "UQ_3118c4db1064a544d9c08b944f2" UNIQUE ("email_address"), CONSTRAINT "PK_519fa28e9620ff7e67759daa754" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."CounsellingBookings_status_enum" AS ENUM('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "CounsellingBookings" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "startsAt" TIMESTAMP NOT NULL, "endsAt" TIMESTAMP, "durationMinutes" integer NOT NULL, "priceAtBooking" numeric NOT NULL, "status" "public"."CounsellingBookings_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "meetingLink" character varying, "locationText" character varying, "reference" character varying, "clientNotes" text, "counsellorNotes" text, "attended" boolean NOT NULL DEFAULT false, "paidAt" TIMESTAMP, "transaction_ref" character varying, "hasRescheduled" boolean NOT NULL DEFAULT false, "userId" integer, "counsellingId" integer, "counsellorId" integer, CONSTRAINT "UQ_8483f2a3de260be094fa10a68a0" UNIQUE ("reference"), CONSTRAINT "PK_f223f100f170ce9d529d0b4d940" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2cee2b693dd857875fb8923a0" ON "CounsellingBookings" ("startsAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_26e2feb72ca164892e984daf4e" ON "CounsellingBookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_40f46d82a127e7439c85f21c7d" ON "CounsellingBookings" ("userId", "counsellingId") `);
        await queryRunner.query(`CREATE TYPE "public"."refund_request_type_enum" AS ENUM('FULL', 'PARTIAL', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."refund_request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED')`);
        await queryRunner.query(`CREATE TYPE "public"."refund_paid_for_enum" AS ENUM('EVENT', 'COUNSELLING', 'COURSE', 'BOOK')`);
        await queryRunner.query(`CREATE TABLE "RefundRequests" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "type" "public"."refund_request_type_enum" NOT NULL, "status" "public"."refund_request_status_enum" NOT NULL DEFAULT 'PENDING', "paidFor" "public"."refund_paid_for_enum" NOT NULL, "requestedAmount" numeric(12,2) NOT NULL, "approvedAmount" numeric(12,2), "reason" text, "approvedAt" TIMESTAMP, "processedAt" TIMESTAMP, "externalReference" character varying, "userId" integer, "registrationId" integer, "counsellingBookingId" integer, "transactionId" integer, "requestedById" integer, "approvedById" integer, CONSTRAINT "PK_7fe6f276e83e1ff810fdfad77b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6f7f8f70df10c3bb1f62ba39f" ON "RefundRequests" ("registrationId", "status") `);
        await queryRunner.query(`CREATE TABLE "post_comments" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "body" text NOT NULL, "userId" integer NOT NULL, "postId" integer NOT NULL, CONSTRAINT "PK_2e99e04b4a1b31de6f833c18ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_likes" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "postId" integer NOT NULL, CONSTRAINT "PK_e4ac7cb9daf243939c6eabb2e0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_shares" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "postId" integer NOT NULL, CONSTRAINT "PK_41290cd17ae407e8d73aaa4fa93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying(255), "body" text NOT NULL, "link" character varying(512), "publishAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "shareCount" integer NOT NULL DEFAULT '0', "userId" integer NOT NULL, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_post_publish_at" ON "posts" ("publishAt") `);
        await queryRunner.query(`CREATE TABLE "nugget_comments" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "comment" text NOT NULL, "nugget_id" integer, "user_id" integer, "parent_comment_id" integer, CONSTRAINT "PK_8c06180a468b119ae34ffb6f938" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_nugget_comment_nugget_id" ON "nugget_comments" ("nugget_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nugget_comment_user_id" ON "nugget_comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nugget_comment_parent_id" ON "nugget_comments" ("parent_comment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."nugget_likes_reaction_enum" AS ENUM('LIKE', 'LOVE', 'INSPIRED')`);
        await queryRunner.query(`CREATE TABLE "nugget_likes" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "reaction" "public"."nugget_likes_reaction_enum" NOT NULL DEFAULT 'LIKE', "nugget_id" integer, "user_id" integer, CONSTRAINT "uq_nugget_like_user_reaction" UNIQUE ("nugget_id", "user_id", "reaction"), CONSTRAINT "PK_9ea36885e359dde8d9ee9e53028" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_nugget_like_nugget_id" ON "nugget_likes" ("nugget_id") `);
        await queryRunner.query(`CREATE INDEX "idx_nugget_like_user_id" ON "nugget_likes" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."nuggets_nuggettype_enum" AS ENUM('SINGLE', 'MARRIED', 'PARENT', 'GENERAL')`);
        await queryRunner.query(`CREATE TABLE "nuggets" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "title" character varying(160), "body" text NOT NULL, "nuggetType" "public"."nuggets_nuggettype_enum" NOT NULL DEFAULT 'GENERAL', "sourceAttribution" character varying(120), "publishAt" TIMESTAMP, "pushed" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "shareCount" integer NOT NULL DEFAULT '0', "adminId" integer, CONSTRAINT "PK_322561d360be8a7d3134628cacf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_nugget_publish_at" ON "nuggets" ("publishAt") `);
        await queryRunner.query(`CREATE TYPE "public"."user_follows_status_enum" AS ENUM('ACCEPTED', 'PENDING', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "user_follows" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "status" "public"."user_follows_status_enum" NOT NULL DEFAULT 'ACCEPTED', "isDeleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "follower_id" integer, "followee_id" integer, CONSTRAINT "PK_da8e8793113adf3015952880966" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b340188b3e87d36026b99939c0" ON "user_follows" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."course_purchases_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "course_purchases" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "courseId" integer NOT NULL, "provider" character varying NOT NULL, "providerRef" character varying NOT NULL, "status" "public"."course_purchases_status_enum" NOT NULL DEFAULT 'PENDING', "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', CONSTRAINT "PK_7df47a16a5795b122e83b6e23cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_630f9a764a2b81622839f9de98" ON "course_purchases" ("provider", "providerRef") `);
        await queryRunner.query(`CREATE TABLE "ChallengeReflections" ("id" SERIAL NOT NULL, "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdAt" TIMESTAMP(6) NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleted" boolean NOT NULL DEFAULT false, "suspended" boolean NOT NULL DEFAULT false, "weekNumber" integer, "content" text NOT NULL, "likesCount" integer NOT NULL DEFAULT '0', "isPinned" boolean NOT NULL DEFAULT false, "challengeId" integer, "userId" integer, CONSTRAINT "PK_7736f5b4af384eb7a409af9eaa2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e29403449208b297c39bb42241" ON "ChallengeReflections" ("challengeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9ca2365f532d6ef051fe25a42" ON "ChallengeReflections" ("userId") `);
        await queryRunner.query(`ALTER TABLE "Transactions" ADD CONSTRAINT "FK_f01450fedf7507118ad25dcf41e" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" ADD CONSTRAINT "FK_5d50276e9e00244f55af8c5d2ab" FOREIGN KEY ("prayer_id") REFERENCES "prayers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" ADD CONSTRAINT "FK_93551f53bd7186b0bc71c4da711" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" ADD CONSTRAINT "FK_c6940377af78213f230fa538800" FOREIGN KEY ("parent_comment_id") REFERENCES "prayer_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayer_amens" ADD CONSTRAINT "FK_4cf6f2ddd237a9b2c7fcd11e8ea" FOREIGN KEY ("prayer_id") REFERENCES "prayers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayer_amens" ADD CONSTRAINT "FK_ecbaba6212e16d9282f2097a275" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prayers" ADD CONSTRAINT "FK_25a96949638aac5ecc471e58aac" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_attachments" ADD CONSTRAINT "FK_2cc9808f14a629ef4e5d792f5e2" FOREIGN KEY ("section_id") REFERENCES "lesson_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_sections" ADD CONSTRAINT "FK_641f3a83ba2f6fa20773cbed2cc" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" ADD CONSTRAINT "FK_0753956d7faa262834efd1ff213" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" ADD CONSTRAINT "FK_894f9a6ece16a83dd2fe2c13c81" FOREIGN KEY ("course_progress_id") REFERENCES "UserCourseProgress"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" ADD CONSTRAINT "FK_ddb21a61647fa3530b5c09c9af3" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserCourseProgress" ADD CONSTRAINT "FK_5885c811d65f2617f6603d36572" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserCourseProgress" ADD CONSTRAINT "FK_981a331bbd2bc02b4dcfad1dde1" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_access" ADD CONSTRAINT "FK_4aa2114fe1fdfc3490ca153e1d4" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_access" ADD CONSTRAINT "FK_bffac211c1be67a096c94a7167c" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChallengeTasks" ADD CONSTRAINT "FK_da6edc7fb6ce04a1591331abfbd" FOREIGN KEY ("challengeId") REFERENCES "Challenges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserChallenges" ADD CONSTRAINT "FK_681341311bbaede188ae732e845" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserChallenges" ADD CONSTRAINT "FK_d43e3b151955547925ab5c34a16" FOREIGN KEY ("challengeId") REFERENCES "Challenges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserTaskProgress" ADD CONSTRAINT "FK_f1f9aac6c268a9c1a9b7866c76c" FOREIGN KEY ("userChallengeId") REFERENCES "UserChallenges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserTaskProgress" ADD CONSTRAINT "FK_3d199fec9f5b0fc69f16856c2fd" FOREIGN KEY ("taskId") REFERENCES "ChallengeTasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserPurchases" ADD CONSTRAINT "FK_43af1d1713f42b7c581c860c2d3" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_section_progress" ADD CONSTRAINT "FK_9054350f382126432ff1422d44e" FOREIGN KEY ("sectionId") REFERENCES "lesson_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserBookDownloads" ADD CONSTRAINT "FK_6d36a2e571cb01fb33cd6260a9a" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserBookDownloads" ADD CONSTRAINT "FK_4f3095c93a1ba1f01adba6df956" FOREIGN KEY ("bookId") REFERENCES "Books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserBadges" ADD CONSTRAINT "FK_a1223f6c26bb6fd2c76c7d3172a" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserBadges" ADD CONSTRAINT "FK_02279ab973308e5562393e99779" FOREIGN KEY ("badgeId") REFERENCES "Badges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "section_attachments" ADD CONSTRAINT "FK_cd9d2383c7a8cc6752a69757191" FOREIGN KEY ("section_id") REFERENCES "lesson_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Events" ADD CONSTRAINT "FK_787aada0579ee53af874be33c4a" FOREIGN KEY ("organizerId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" ADD CONSTRAINT "FK_9cd25e01bb36ea34ac9905cd709" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" ADD CONSTRAINT "FK_35ffd8c45284793377576397158" FOREIGN KEY ("eventId") REFERENCES "Events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" ADD CONSTRAINT "FK_f6c024c4682505120a6c845643a" FOREIGN KEY ("transactionId") REFERENCES "Transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Counsellings" ADD CONSTRAINT "FK_ea3ce3a9b99000e33d5e55ab14f" FOREIGN KEY ("counsellorId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" ADD CONSTRAINT "FK_e48a92d35bdd1a3d0779074eb47" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" ADD CONSTRAINT "FK_c3c05cf1c0080d01c44d9114468" FOREIGN KEY ("counsellingId") REFERENCES "Counsellings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" ADD CONSTRAINT "FK_937e98080174321bc9a8b612e29" FOREIGN KEY ("counsellorId") REFERENCES "Admins"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_399de258e6a3ffd62ff9e135edf" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_c944f39d772cb7919a91977bf4e" FOREIGN KEY ("registrationId") REFERENCES "EventRegistrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_425bc435fe7bb640ef4797d693b" FOREIGN KEY ("counsellingBookingId") REFERENCES "CounsellingBookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_963b210993a55169087fc55d084" FOREIGN KEY ("transactionId") REFERENCES "Transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_27406e49453b5c891a82b2c6fa3" FOREIGN KEY ("requestedById") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" ADD CONSTRAINT "FK_10e54aa8b41f96d65475e741051" FOREIGN KEY ("approvedById") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_62817b3571ec31e552a3cae4e1c" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_comments" ADD CONSTRAINT "FK_ac65d744abc05279aee0b290857" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_0c802b35b3e81c1c9a210b134c4" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_shares" ADD CONSTRAINT "FK_0cf5df17d5dac2d43ac01817e94" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" ADD CONSTRAINT "FK_e6b2dd999dde5d9cba217b51566" FOREIGN KEY ("nugget_id") REFERENCES "nuggets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" ADD CONSTRAINT "FK_a6cc59ed2a2f1e142f0a3bc7232" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" ADD CONSTRAINT "FK_d14151578708acc22ca683c4c6a" FOREIGN KEY ("parent_comment_id") REFERENCES "nugget_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nugget_likes" ADD CONSTRAINT "FK_14bf20b8f708690556a6e87d1b2" FOREIGN KEY ("nugget_id") REFERENCES "nuggets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nugget_likes" ADD CONSTRAINT "FK_cb53505489832ce6c9ccd1d613a" FOREIGN KEY ("user_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nuggets" ADD CONSTRAINT "FK_ccda87cbb46d0f250af119db327" FOREIGN KEY ("adminId") REFERENCES "Admins"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_follows" ADD CONSTRAINT "FK_f7af3bf8f2dcba61b4adc108239" FOREIGN KEY ("follower_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_follows" ADD CONSTRAINT "FK_ad9563c49281be94000f50a4308" FOREIGN KEY ("followee_id") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChallengeReflections" ADD CONSTRAINT "FK_e29403449208b297c39bb422414" FOREIGN KEY ("challengeId") REFERENCES "Challenges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChallengeReflections" ADD CONSTRAINT "FK_e9ca2365f532d6ef051fe25a42e" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ChallengeReflections" DROP CONSTRAINT "FK_e9ca2365f532d6ef051fe25a42e"`);
        await queryRunner.query(`ALTER TABLE "ChallengeReflections" DROP CONSTRAINT "FK_e29403449208b297c39bb422414"`);
        await queryRunner.query(`ALTER TABLE "user_follows" DROP CONSTRAINT "FK_ad9563c49281be94000f50a4308"`);
        await queryRunner.query(`ALTER TABLE "user_follows" DROP CONSTRAINT "FK_f7af3bf8f2dcba61b4adc108239"`);
        await queryRunner.query(`ALTER TABLE "nuggets" DROP CONSTRAINT "FK_ccda87cbb46d0f250af119db327"`);
        await queryRunner.query(`ALTER TABLE "nugget_likes" DROP CONSTRAINT "FK_cb53505489832ce6c9ccd1d613a"`);
        await queryRunner.query(`ALTER TABLE "nugget_likes" DROP CONSTRAINT "FK_14bf20b8f708690556a6e87d1b2"`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" DROP CONSTRAINT "FK_d14151578708acc22ca683c4c6a"`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" DROP CONSTRAINT "FK_a6cc59ed2a2f1e142f0a3bc7232"`);
        await queryRunner.query(`ALTER TABLE "nugget_comments" DROP CONSTRAINT "FK_e6b2dd999dde5d9cba217b51566"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_ae05faaa55c866130abef6e1fee"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_0cf5df17d5dac2d43ac01817e94"`);
        await queryRunner.query(`ALTER TABLE "post_shares" DROP CONSTRAINT "FK_0c802b35b3e81c1c9a210b134c4"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_ac65d744abc05279aee0b290857"`);
        await queryRunner.query(`ALTER TABLE "post_comments" DROP CONSTRAINT "FK_62817b3571ec31e552a3cae4e1c"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_10e54aa8b41f96d65475e741051"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_27406e49453b5c891a82b2c6fa3"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_963b210993a55169087fc55d084"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_425bc435fe7bb640ef4797d693b"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_c944f39d772cb7919a91977bf4e"`);
        await queryRunner.query(`ALTER TABLE "RefundRequests" DROP CONSTRAINT "FK_399de258e6a3ffd62ff9e135edf"`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" DROP CONSTRAINT "FK_937e98080174321bc9a8b612e29"`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" DROP CONSTRAINT "FK_c3c05cf1c0080d01c44d9114468"`);
        await queryRunner.query(`ALTER TABLE "CounsellingBookings" DROP CONSTRAINT "FK_e48a92d35bdd1a3d0779074eb47"`);
        await queryRunner.query(`ALTER TABLE "Counsellings" DROP CONSTRAINT "FK_ea3ce3a9b99000e33d5e55ab14f"`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" DROP CONSTRAINT "FK_f6c024c4682505120a6c845643a"`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" DROP CONSTRAINT "FK_35ffd8c45284793377576397158"`);
        await queryRunner.query(`ALTER TABLE "EventRegistrations" DROP CONSTRAINT "FK_9cd25e01bb36ea34ac9905cd709"`);
        await queryRunner.query(`ALTER TABLE "Events" DROP CONSTRAINT "FK_787aada0579ee53af874be33c4a"`);
        await queryRunner.query(`ALTER TABLE "section_attachments" DROP CONSTRAINT "FK_cd9d2383c7a8cc6752a69757191"`);
        await queryRunner.query(`ALTER TABLE "UserBadges" DROP CONSTRAINT "FK_02279ab973308e5562393e99779"`);
        await queryRunner.query(`ALTER TABLE "UserBadges" DROP CONSTRAINT "FK_a1223f6c26bb6fd2c76c7d3172a"`);
        await queryRunner.query(`ALTER TABLE "UserBookDownloads" DROP CONSTRAINT "FK_4f3095c93a1ba1f01adba6df956"`);
        await queryRunner.query(`ALTER TABLE "UserBookDownloads" DROP CONSTRAINT "FK_6d36a2e571cb01fb33cd6260a9a"`);
        await queryRunner.query(`ALTER TABLE "user_section_progress" DROP CONSTRAINT "FK_9054350f382126432ff1422d44e"`);
        await queryRunner.query(`ALTER TABLE "UserPurchases" DROP CONSTRAINT "FK_43af1d1713f42b7c581c860c2d3"`);
        await queryRunner.query(`ALTER TABLE "UserTaskProgress" DROP CONSTRAINT "FK_3d199fec9f5b0fc69f16856c2fd"`);
        await queryRunner.query(`ALTER TABLE "UserTaskProgress" DROP CONSTRAINT "FK_f1f9aac6c268a9c1a9b7866c76c"`);
        await queryRunner.query(`ALTER TABLE "UserChallenges" DROP CONSTRAINT "FK_d43e3b151955547925ab5c34a16"`);
        await queryRunner.query(`ALTER TABLE "UserChallenges" DROP CONSTRAINT "FK_681341311bbaede188ae732e845"`);
        await queryRunner.query(`ALTER TABLE "ChallengeTasks" DROP CONSTRAINT "FK_da6edc7fb6ce04a1591331abfbd"`);
        await queryRunner.query(`ALTER TABLE "course_access" DROP CONSTRAINT "FK_bffac211c1be67a096c94a7167c"`);
        await queryRunner.query(`ALTER TABLE "course_access" DROP CONSTRAINT "FK_4aa2114fe1fdfc3490ca153e1d4"`);
        await queryRunner.query(`ALTER TABLE "UserCourseProgress" DROP CONSTRAINT "FK_981a331bbd2bc02b4dcfad1dde1"`);
        await queryRunner.query(`ALTER TABLE "UserCourseProgress" DROP CONSTRAINT "FK_5885c811d65f2617f6603d36572"`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" DROP CONSTRAINT "FK_ddb21a61647fa3530b5c09c9af3"`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" DROP CONSTRAINT "FK_894f9a6ece16a83dd2fe2c13c81"`);
        await queryRunner.query(`ALTER TABLE "UserLessonProgress" DROP CONSTRAINT "FK_0753956d7faa262834efd1ff213"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe"`);
        await queryRunner.query(`ALTER TABLE "lesson_sections" DROP CONSTRAINT "FK_641f3a83ba2f6fa20773cbed2cc"`);
        await queryRunner.query(`ALTER TABLE "lesson_attachments" DROP CONSTRAINT "FK_2cc9808f14a629ef4e5d792f5e2"`);
        await queryRunner.query(`ALTER TABLE "prayers" DROP CONSTRAINT "FK_25a96949638aac5ecc471e58aac"`);
        await queryRunner.query(`ALTER TABLE "prayer_amens" DROP CONSTRAINT "FK_ecbaba6212e16d9282f2097a275"`);
        await queryRunner.query(`ALTER TABLE "prayer_amens" DROP CONSTRAINT "FK_4cf6f2ddd237a9b2c7fcd11e8ea"`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" DROP CONSTRAINT "FK_c6940377af78213f230fa538800"`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" DROP CONSTRAINT "FK_93551f53bd7186b0bc71c4da711"`);
        await queryRunner.query(`ALTER TABLE "prayer_comments" DROP CONSTRAINT "FK_5d50276e9e00244f55af8c5d2ab"`);
        await queryRunner.query(`ALTER TABLE "Transactions" DROP CONSTRAINT "FK_f01450fedf7507118ad25dcf41e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9ca2365f532d6ef051fe25a42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e29403449208b297c39bb42241"`);
        await queryRunner.query(`DROP TABLE "ChallengeReflections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_630f9a764a2b81622839f9de98"`);
        await queryRunner.query(`DROP TABLE "course_purchases"`);
        await queryRunner.query(`DROP TYPE "public"."course_purchases_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b340188b3e87d36026b99939c0"`);
        await queryRunner.query(`DROP TABLE "user_follows"`);
        await queryRunner.query(`DROP TYPE "public"."user_follows_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_publish_at"`);
        await queryRunner.query(`DROP TABLE "nuggets"`);
        await queryRunner.query(`DROP TYPE "public"."nuggets_nuggettype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_like_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_like_nugget_id"`);
        await queryRunner.query(`DROP TABLE "nugget_likes"`);
        await queryRunner.query(`DROP TYPE "public"."nugget_likes_reaction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_comment_parent_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_comment_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nugget_comment_nugget_id"`);
        await queryRunner.query(`DROP TABLE "nugget_comments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_post_publish_at"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "post_shares"`);
        await queryRunner.query(`DROP TABLE "post_likes"`);
        await queryRunner.query(`DROP TABLE "post_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6f7f8f70df10c3bb1f62ba39f"`);
        await queryRunner.query(`DROP TABLE "RefundRequests"`);
        await queryRunner.query(`DROP TYPE "public"."refund_paid_for_enum"`);
        await queryRunner.query(`DROP TYPE "public"."refund_request_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."refund_request_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40f46d82a127e7439c85f21c7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26e2feb72ca164892e984daf4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2cee2b693dd857875fb8923a0"`);
        await queryRunner.query(`DROP TABLE "CounsellingBookings"`);
        await queryRunner.query(`DROP TYPE "public"."CounsellingBookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "Admins"`);
        await queryRunner.query(`DROP TYPE "public"."Admins_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a84583a29ffcc0855944cada3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9aaea653f378930280d4c4adfb"`);
        await queryRunner.query(`DROP TABLE "Counsellings"`);
        await queryRunner.query(`DROP TYPE "public"."Counsellings_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Counsellings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Counsellings_mode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88a8ce1237cc41db00d76b9c38"`);
        await queryRunner.query(`DROP TABLE "EventRegistrations"`);
        await queryRunner.query(`DROP TYPE "public"."event_registration_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dba9ac34c81dd23102f2e486f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76b3852578992c8d734d9307c6"`);
        await queryRunner.query(`DROP TABLE "Events"`);
        await queryRunner.query(`DROP TYPE "public"."Events_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd9d2383c7a8cc6752a6975719"`);
        await queryRunner.query(`DROP TABLE "section_attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7aca27064e9a12cebda5ad8651"`);
        await queryRunner.query(`DROP TABLE "UserBadges"`);
        await queryRunner.query(`DROP TABLE "Badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56048469fcc831362af2268273"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5ec900b10e0b63ffe766311d1"`);
        await queryRunner.query(`DROP TABLE "UserBookDownloads"`);
        await queryRunner.query(`DROP TYPE "public"."user_book_download_ownership_status_enum"`);
        await queryRunner.query(`DROP TABLE "Books"`);
        await queryRunner.query(`DROP TYPE "public"."Books_accesstype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Books_ownershiptype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cc397afbe76ce6dd15856e101"`);
        await queryRunner.query(`DROP TABLE "user_section_progress"`);
        await queryRunner.query(`DROP TYPE "public"."user_section_progress_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97f8e3d9c172164216e43ca238"`);
        await queryRunner.query(`DROP TABLE "UserPurchases"`);
        await queryRunner.query(`DROP TYPE "public"."UserPurchases_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."UserPurchases_itemtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98b1f78ec350bd9cab8cbcfb5b"`);
        await queryRunner.query(`DROP TABLE "UserTaskProgress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51e41d4e6713142e1589f859f8"`);
        await queryRunner.query(`DROP TABLE "UserChallenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b363ac79f844603c4ecfb964d9"`);
        await queryRunner.query(`DROP TABLE "Challenges"`);
        await queryRunner.query(`DROP TYPE "public"."Challenges_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Challenges_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Challenges_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Challenges_community_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da6edc7fb6ce04a1591331abfb"`);
        await queryRunner.query(`DROP TABLE "ChallengeTasks"`);
        await queryRunner.query(`DROP TYPE "public"."ChallengeTasks_cadence_enum"`);
        await queryRunner.query(`DROP TABLE "Users"`);
        await queryRunner.query(`DROP TYPE "public"."Users_marital_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Users_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Users_auth_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02a4cae0a5ab7f68e5c63b18f5"`);
        await queryRunner.query(`DROP TABLE "course_access"`);
        await queryRunner.query(`DROP TYPE "public"."course_access_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."course_access_kind_enum"`);
        await queryRunner.query(`DROP TABLE "UserCourseProgress"`);
        await queryRunner.query(`DROP TYPE "public"."UserCourseProgress_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3aff9a5f008a7ae618ea29f74d"`);
        await queryRunner.query(`DROP TABLE "UserLessonProgress"`);
        await queryRunner.query(`DROP TYPE "public"."UserLessonProgress_status_enum"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TYPE "public"."courses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."courses_accesstype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39a94200768edfbf102291bb34"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP TYPE "public"."lessons_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3650404571311a3992c5467ae7"`);
        await queryRunner.query(`DROP TABLE "lesson_sections"`);
        await queryRunner.query(`DROP TABLE "lesson_attachments"`);
        await queryRunner.query(`DROP TYPE "public"."lesson_attachments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayers_is_visible"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayers_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayers_last_activity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayers_user_id"`);
        await queryRunner.query(`DROP TABLE "prayers"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_amen_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_amen_prayer_id"`);
        await queryRunner.query(`DROP TABLE "prayer_amens"`);
        await queryRunner.query(`DROP TYPE "public"."prayer_amens_reaction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_comment_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_comment_parent_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_comment_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prayer_comment_prayer_id"`);
        await queryRunner.query(`DROP TABLE "prayer_comments"`);
        await queryRunner.query(`DROP TABLE "Transactions"`);
        await queryRunner.query(`DROP TYPE "public"."Transactions_paid_for_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Transactions_status_enum"`);
    }

}
